name: Build Kivy APK Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Build APK using Buildozer (Podman)
        run: |
          podman run --rm \
            -v ${{ github.workspace }}:/home/buildozer/buildozer \
            ghcr.io/kivy/buildozer:latest \
            buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
